services:
  simple-nats:
    build:
      context: .
      dockerfile: Dockerfile
    image: simple-nats:latest
    container_name: simple-nats
    ports:
      - 4222:4222
    networks:
      - nats
  nats-box:
    container_name: nats-box
    image: natsio/nats-box:latest
    command: ["sleep", "infiniy"]
    networks:
      - nats
networks:
  nats:
    name: nats
